preset: psr12

enabled:
  - symfony_braces

disabled:
  - const_visibility_required
  - psr12_braces

finder:
  not-name:
    - Php80LanguageFeaturesTest.php
    - SemiReservedWordsAsMethods.php
